version: "3.9"

services:
  brownie-workshop:
    # image: utkusarioglu/python-devcontainer:1.0.14
    image: utkusarioglu/python-devcontainer:experiment-feat-music-sequencer-8
    container_name: brownie-workshop
    environment:
      PYTHONPATH: /utkusarioglu-com/workshops/brownie-workshop
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu-com/workshops/brownie-workshop

  brownie-workshop-redis-stack:
    image: redis/redis-stack:7.2.0-v6-x86_64
    container_name: brownie-workshop-redis-stack
    ports:
      - 6379:6379
      - 8001:8001

  brownie-workshop-mongodb-community-server:
    container_name: brownie-workshop-mongodb-community-server
    image: mongodb/mongodb-community-server:7.0.4-ubuntu2204
    volumes:
      - type: bind
        source: ../config/mongodb
        target: /mongo_config
      - type: volume
        source: mongodb-community-server-data
        target: /data/db
    # environment:
    #   - MONGODB_INITDB_ROOT_USERNAME_FILE=/mongo_config/USERNAME
    #   - MONGODB_INITDB_ROOT_PASSWORD_FILE=/mongo_config/PASSWORD
    ports:
      - 27017:27017

volumes:
  mongodb-community-server-data:
    name: brownie-workshop-mongodb-community-server-data
