version: "3.9"

services:
  brownie-workshop:
    # image: utkusarioglu/python-devcontainer:1.0.14
    image: utkusarioglu/python-devcontainer:experiment-feat-music-sequencer-8
    environment:
      PYTHONPATH: /utkusarioglu-com/workshops/brownie-workshop
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu-com/workshops/brownie-workshop
